# Site settings
title: Julianna's Blog
email: contact@juliannabudding.com
description: A blog about web design and frontend development by an experienced designer and frontend developer in training
  # this means to ignore newlines until "baseurl:" write > # to make # show up
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juliannascruggs.github.io/" # the base hostname & protocol for your site
twitter_username: juliannascruggs
github_username:  juliannascruggs

# Build settings
markdown: kramdown
